# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.provision :puppet do |puppet|
	puppet.manifest_path = 'puppet/manifests'
	puppet.module_path = 'puppet/modules'
	puppet.options = '--verbose'
end
